[package]
name = "params"
version = "0.0.3"
authors = ["Skyler Lipthay <skyler.lipthay@gmail.com>"]
description = "A multi-source request parameters parser for Iron."
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/iron/params"
documentation = "http://ironframework.io/doc/params/index.html"

[dependencies]
bodyparser = "0.3"
formdata = "0.7"
iron = "0.3"
num = "0.1"
plugin = "0.2"
serde = "0.7"
serde_json = "0.7"
urlencoded = "0.3"
